import trimesh, sys
m = trimesh.load("hook.stl")
V = len(m.vertices)
F = len(m.faces)
E = len(m.edges_unique)
print(f"vertices         : {V}")
print(f"faces (facets)   : {F}")
print(f"unique edges     : {E}")
print(f"3*F              : {3*F}")
print(f"edges == 3*F     : {E == 3*F}")
print(f"is_watertight    : {m.is_watertight}")
print(f"is_winding_consistent: {m.is_winding_consistent}")
print(f"body_count (shells): {getattr(m, 'body_count', 'N/A')}")
if m.is_watertight:
    print(f"volume           : {m.volume}")
sys.exit(0 if (E == 3*F and m.is_watertight) else 1)