#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
keyword_to_params.py
将风格关键词转为 Blender Python 代码（bpy 调用），输出到 stdout 或文件。
支持 --style <风格名> 查询 style_mapping.json 并生成 Blender Python API 代码。
支持 --check_output 自检模式：验证输出格式是否包含关键 bpy API 调用。
"""

import argparse
import json
import math
import os
import sys

# ---------- 参数范围常量（摄影理论/行业常规） ----------
LIGHT_MIN = 75        # 室内主光强度下限 W/m²
LIGHT_MAX = 150       # 室内主光强度上限 W/m²
KELVIN_MIN = 2700     # 暖光最低色温 K
KELVIN_MAX = 6500     # 冷光最高色温 K
ENV_RATIO_MIN = 0.0
ENV_RATIO_MAX = 1.0
REFLECT_MIN = 0.0
REFLECT_MAX = 1.0
ROUGH_MIN = 0.0
ROUGH_MAX = 1.0
CAM_HEIGHT_MIN = 0.3
CAM_HEIGHT_MAX = 3.0
FOV_MIN = 15.0
FOV_MAX = 90.0


def load_mapping(path="style_mapping.json"):
    """加载风格映射 JSON；文件不存在或格式错误时给出明确报错并退出非 0。"""
    if not os.path.exists(path):
        sys.stderr.write("[ERROR] 风格映射文件不存在: %s\n" % path)
        sys.exit(2)
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        sys.stderr.write("[ERROR] 风格映射文件 JSON 格式错误: %s\n" % e)
        sys.exit(2)
    except Exception as e:
        sys.stderr.write("[ERROR] 读取风格映射文件失败: %s\n" % e)
        sys.exit(2)


def clamp(value, lo, hi):
    try:
        v = float(value)
    except (TypeError, ValueError):
        return float(lo)
    return max(float(lo), min(float(hi), v))


def get_style_params(mapping, style):
    """根据风格键查询参数；若不存在，使用 _fallback 并在 stderr 提示。"""
    if not style:
        sys.stderr.write("[WARN] 未指定风格，使用 _fallback 默认参数\n")
        return mapping.get("_fallback"), True
    if style in mapping:
        return mapping[style], False
    sys.stderr.write("[WARN] 风格 '%s' 不在映射表中，使用 _fallback 默认参数\n" % style)
    return mapping.get("_fallback"), True


def validate_params(p):
    """对参数做合理范围校验与修正，返回 (cleaned_params, warnings_list)。"""
    warnings = []
    light = dict(p.get("光照", {}))
    mat = dict(p.get("材质", {}))
    comp = dict(p.get("构图", {}))

    raw_light = light.get("主光强度", 100)
    light["主光强度"] = clamp(raw_light, LIGHT_MIN, LIGHT_MAX)
    if light["主光强度"] != clamp(raw_light, LIGHT_MIN - 1, LIGHT_MAX + 1):
        warnings.append("主光强度已修正到 [%d,%d]" % (LIGHT_MIN, LIGHT_MAX))

    light["色温"] = clamp(light.get("色温", 5000), KELVIN_MIN, KELVIN_MAX)

    env_raw = light.get("环境光强度", 0.4)
    light["环境光强度"] = clamp(env_raw, ENV_RATIO_MIN, ENV_RATIO_MAX)
    if env_raw > ENV_RATIO_MAX:
        warnings.append("环境光强度已限制到 1.0 以下避免过曝")

    mat["反射度"] = clamp(mat.get("反射度", 0.5), REFLECT_MIN, REFLECT_MAX)
    mat["粗糙度"] = clamp(mat.get("粗糙度", 0.5), ROUGH_MIN, ROUGH_MAX)

    comp["相机高度"] = clamp(comp.get("相机高度", 1.2), CAM_HEIGHT_MIN, CAM_HEIGHT_MAX)
    comp["目标高度"] = clamp(comp.get("目标高度", 0.8), 0.0, 3.0)
    comp["视角"] = clamp(comp.get("视角", 35), FOV_MIN, FOV_MAX)

    return {"光照": light, "材质": mat, "构图": comp}, warnings


def kelvin_to_rgb(k):
    """粗略的色温→RGB（用于 Blender 世界环境节点）。返回 (r,g,b) 0-1。"""
    k = max(1000, min(40000, float(k)))
    temp = k / 100.0
    if temp <= 66:
        r = 255
        if temp > 0:
            g = 99.4708025861 * math.log(temp) - 161.1195681661
            g = max(0, g)
        else:
            g = 0
        if temp <= 19:
            b = 0
        else:
            b = 138.5177312231 * math.log(temp - 10) - 305.0447927307
            b = max(0, b)
    else:
        r = 329.698727446 * ((temp - 60) ** -0.1332047592)
        g = 288.1221695283 * ((temp - 60) ** -0.0755148492)
        b = 255
    return (min(1.0, r / 255.0), min(1.0, g / 255.0), min(1.0, b / 255.0))


def generate_blender_code(style_name, params, out_dir=None):
    """生成 Blender Python API 代码字符串（可作为 .py 在 blender --python 下运行）。"""
    light = params["光照"]
    mat = params["材质"]
    comp = params["构图"]

    main_w = float(light["主光强度"])
    kelvin = float(light["色温"])
    env_ratio = float(light["环境光强度"])
    env_strength = main_w * env_ratio
    reflect = float(mat["反射度"])
    rough = float(mat["粗糙度"])
    base_color = mat.get("主色", "#A0A0A0")
    cam_h = float(comp["相机高度"])
    target_h = float(comp["目标高度"])
    fov = float(comp["视角"])
    if out_dir is None:
        out_dir = comp.get("输出目录", "./render_out")
    safe_style = style_name or "default"

    r, g, b = kelvin_to_rgb(kelvin)
    fov_rad = fov * math.pi / 180.0

    # 解析十六进制颜色
    def hx(c):
        return int(c[1:3], 16) / 255.0, int(c[3:5], 16) / 255.0, int(c[5:7], 16) / 255.0
    br, bgg, bb = hx(base_color) if isinstance(base_color, str) and len(base_color) == 7 else (0.6, 0.6, 0.6)

    code = []
    code.append("# -*- coding: utf-8 -*-")
    code.append("# Auto-generated by keyword_to_params.py for style: %s" % safe_style)
    code.append("import bpy")
    code.append("import os")
    code.append("import sys")
    code.append("")
    code.append("OUT_DIR = r\"%s\"" % out_dir)
    code.append("os.makedirs(OUT_DIR, exist_ok=True)")
    code.append("")
    code.append("# 清空默认场景")
    code.append("bpy.ops.wm.read_factory_settings(use_empty=True)")
    code.append("")
    code.append("# ---------- 光照 ----------")
    code.append("# 主光源（区域光，模拟软光箱）")
    code.append("bpy.ops.object.light_add(type='AREA', location=(0, -3, 2.5))")
    code.append("main_light = bpy.context.active_object")
    code.append("main_light.data.energy = %.4f" % main_w)
    code.append("main_light.data.size = 2.0")
    code.append("main_light.data.color = (%.4f, %.4f, %.4f)" % (r, g, b))
    code.append("")
    code.append("# 环境光（世界环境），强度为主光 20%-50%")
    code.append("world = bpy.context.scene.world")
    code.append("world.use_nodes = True")
    code.append("bg = world.node_tree.nodes.get('Background')")
    code.append("if bg is None:")
    code.append("    bg = world.node_tree.nodes.new(type='ShaderNodeBackground')")
    code.append("bpy.context.scene.world.node_tree.nodes['Background'].inputs['Color'].default_value = (%.4f, %.4f, %.4f, 1.0)" % (r, g, b))
    code.append("bpy.context.scene.world.node_tree.nodes['Background'].inputs['Strength'].default_value = %.4f" % env_ratio)
    code.append("")
    code.append("# ---------- 相机 ----------")
    code.append("bpy.ops.object.camera_add(location=(3.5, -3.5, %.4f))" % cam_h)
    code.append("cam = bpy.context.active_object")
    code.append("bpy.context.scene.camera = cam")
    code.append("cam.data.lens_unit = 'FOV'")
    code.append("cam.data.angle = %.4f  # %.1f 度" % (fov_rad, fov))
    code.append("")
    code.append("# 注视目标点")
    code.append("bpy.ops.object.empty_add(location=(0, 0, %.4f))" % target_h)
    code.append("target = bpy.context.active_object")
    code.append("con = cam.constraints.new(type='TRACK_TO')")
    code.append("con.target = target")
    code.append("con.track_axis = 'TRACK_NEGATIVE_Z'")
    code.append("con.up_axis = 'UP_Y'")
    code.append("")
    code.append("# ---------- 产品占位立方体（应用材质） ----------")
    code.append("bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, %.4f))" % target_h)
    code.append("prod = bpy.context.active_object")
    code.append("mat = bpy.data.materials.new(name=\"Mat_%s\")" % safe_style)
    code.append("mat.use_nodes = True")
    code.append("bsdf = mat.node_tree.nodes.get('Principled BSDF')")
    code.append("if bsdf:")
    code.append("    bsdf.inputs['Base Color'].default_value = (%.4f, %.4f, %.4f, 1.0)" % (br, bgg, bb))
    code.append("    bsdf.inputs['Roughness'].default_value = %.4f" % rough)
    code.append("    bsdf.inputs['Metallic'].default_value = %.4f" % reflect)
    code.append("prod.data.materials.append(mat)")
    code.append("")
    code.append("# 地面")
    code.append("bpy.ops.mesh.primitive_plane_add(size=10, location=(0, 0, 0))")
    code.append("bpy.context.active_object.name = \"Floor\"")
    code.append("")
    code.append("# ---------- 渲染参数 ----------")
    code.append("bpy.context.scene.render.resolution_x = 1920")
    code.append("bpy.context.scene.render.resolution_y = 1080")
    code.append("bpy.context.scene.render.samples = 128")
    code.append("bpy.context.scene.render.filepath = os.path.join(OUT_DIR, \"%s_render.png\")" % safe_style)
    code.append("")
    code.append("# ---------- 执行渲染 ----------")
    code.append("bpy.ops.render.render(write_still=True)")
    code.append("sys.stdout.write(\"[OK] 完成渲染: \" + bpy.context.scene.render.filepath + \"\\n\")")
    return "\n".join(code) + "\n"


def main():
    parser = argparse.ArgumentParser(description="风格关键词转 Blender 参数脚本")
    parser.add_argument("--style", default=None, help="风格关键词，如 北欧 / 日式 / 奢华 / 工业 / 温馨")
    parser.add_argument("--mapping", default="style_mapping.json", help="风格映射 JSON 路径")
    parser.add_argument("--out", default=None, help="生成代码输出文件路径（默认 stdout）")
    parser.add_argument("--check_output", action="store_true", help="自检：验证输出格式包含关键 bpy API 调用")
    args = parser.parse_args()

    mapping = load_mapping(args.mapping)
    raw_params, used_fallback = get_style_params(mapping, args.style)
    params, warnings = validate_params(raw_params)
    for w in warnings:
        sys.stderr.write("[WARN] %s\n" % w)

    code = generate_blender_code(args.style or "default", params)

    if args.check_output:
        required = [
            "bpy.context.scene.world.node_tree.nodes",
            "bpy.ops.object.light_add",
            "bpy.context.scene.camera",
            "bpy.ops.render.render",
        ]
        missing = [k for k in required if k not in code]
        if missing:
            sys.stderr.write("[FAIL] 输出缺少关键 API: %s\n" % missing)
            sys.exit(1)
        sys.stdout.write(code)
        sys.stderr.write("[OK] check_output 通过\n")
        return

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(code)
        sys.stderr.write("[OK] 已写入 %s\n" % args.out)
    else:
        sys.stdout.write(code)


if __name__ == "__main__":
    main()